In [1]:
import numpy as np

### __Создание массивов с помощью функций генерирующих псевдослучайные числа__

__np.random.rand__ - создает массив заданной размерности, заполненный числами от 0 до 1 (1 в диапазон не входит)

In [2]:
np.random.rand(4, 3)

array([[0.37736366, 0.20741597, 0.08535949],
       [0.71866529, 0.38245276, 0.13782703],
       [0.55646993, 0.12903247, 0.5408041 ],
       [0.60721671, 0.16720241, 0.02684765]])

__np.random.randint__ - создает массив целых чисел в заданном диапазоне (верхняя граница не входит в диапазон) и с заданной размерностью

In [3]:
np.random.randint(-3, 3, size = (2, 3, 2))

array([[[ 2,  2],
        [ 2, -2],
        [-1,  2]],

       [[-3,  2],
        [-1, -2],
        [ 0,  1]]])

### __Создание массива из функции__

In [4]:
# создадим собственную функцию, которая принимает два числа и 
# возводит первое число в степень второго
def power(i, j):
    return i ** j

Применим эту функцию к каждой ячейке (координатам) массива с размерностью (3, 3)

__np.fromfunction()__ - берет координаты (i, j) каждой ячейки и передает их в собственную функцию

In [5]:
np.fromfunction(power, (3, 3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

### __Матрица csr и метод .toarray()__

In [6]:
# создадим матрицу с преобладанием нулевых значений
A = np.array([[2, 0, 0, 1, 0, 0, 0], [0, 0, 3, 0, 0, 2, 0], [0, 0, 0, 1, 0, 0, 0]])
A

array([[2, 0, 0, 1, 0, 0, 0],
       [0, 0, 3, 0, 0, 2, 0],
       [0, 0, 0, 1, 0, 0, 0]])

In [7]:
# Преобразуем матрицу в формат csr
# импортируем функцию csr_matrix()
from scipy.sparse import csr_matrix

# и применим ее к матрице А
B = csr_matrix(A)
print(B)

  (0, 0)	2
  (0, 3)	1
  (1, 2)	3
  (1, 5)	2
  (2, 3)	1


In [8]:
# вернем матрицу csr обратно в формат массива Numpy
C = B.toarray()
C

array([[2, 0, 0, 1, 0, 0, 0],
       [0, 0, 3, 0, 0, 2, 0],
       [0, 0, 0, 1, 0, 0, 0]], dtype=int32)

### __Индекс элемента массива__

In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# посмотрим на измерения и количество элементов
a.shape

(2, 3)

In [11]:
# Выведем первый элемент первого (внешнего) измерения
a[0]

array([1, 2, 3])

In [12]:
# Второй индекс позволяет обратиться, например, к первому элементу, первого вектора
a[0][0]

1

In [13]:
# выведем значение 6
a[1][2]

6

### __Срез массива__

__Одномерный массив__

In [14]:
# создадим одномерный массив
b = np.array([1, 2, 3, 4, 5, 6, 7, 8])
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
# возьмем каждый второй лемент в интервале с 1-го по 6-й индекс
b[1:6:2]

array([2, 4, 6])

__Двумерный массив__

In [16]:
# создадим двумерный массив
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
# сделаем срез из первой строки (внешнее измерение) и первых двух столбцов (внутренне измерение)
c[0, :2]

array([1, 2])

In [18]:
# возьмем обе строки во втором столбце
c[:, 1]

array([2, 6])

In [19]:
# выведем элемент в первой строке и первом столбце
c[0, 0]

# c[0, 0] == c[0][0]

1

In [20]:
# допускаются срезы с отрицательным индексом
c[-1, -1]

8

In [21]:
# возьмем всю вторую строку и каждый второй столбец
c[1, ::2]

array([5, 7])

__Трехмерный массив__

In [22]:
# Создадим массив с тремя измерениями
# Наш 3D массив представляет собой четыре матрицы 2х2

# -1 означает, что Питон сам рассчитает количество элементов в этом измерении
d = np.arange(16).reshape(4, 2, -1)
d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [23]:
# Выведем значение 10. Если идти снаружи вовнутрь, получается, что это 3 матрица [2]
# второй вектор [1] и первый элемент [0]
d[2, 1, 0]

10

In [24]:
# для срезов понадобится две запятых
# выведем третью и четвертую матрицу [2:]
# и в них сторую строку [1] и все столбцы [:]
d[2:, 1, :]

array([[10, 11],
       [14, 15]])

In [25]:
# если указать только один срез, будем работать только во внешнем
# измерении, т.е. с матрицами
# выведем первые две матрицы
d[:2]

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
# выведем первые строки каждой матрицы
d[:, 0, :]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

### __Оси массива__

__Массив 2D__

In [27]:
arr_2D = np.array([[1, 2], [3, 4]])
arr_2D

array([[1, 2],
       [3, 4]])

Сложение вдоль первой оси (axis = 0)

In [28]:
# найдем сумму по столбцам (вдоль оси 0)
np.sum(arr_2D, axis = 0)

array([4, 6])

Сложение вдоль второй оси (axis = 1)

In [29]:
# найдем сумму по строкам (вдоль оси 1)
np.sum(arr_2D, axis = 1)

array([3, 7])

При таких операциях говорят, что мы агрегируем (aggregate) данные и сворачиваем (collapse) или сокращаем (reduce) измерения вдоль определенной оси. И действительно, в каждой из описанных выше операций двумерный массив превратился в одномерный.

Сложение вдоль обеих осей (axis = (0, 1))

In [30]:
np.sum(arr_2D, axis = (0, 1))

10

In [31]:
# если параметр axis не указывать, сумма также будет расчитана по всем элементам массива
np.sum(arr_2D)

# в этом случае стоит значение по умолчанию axis = None

10

In [32]:
# допускаются отрицательное значение параметра axis. Параметр axis = -1
# соответствует последней по счету оси, то есть оси 1
np.sum(arr_2D, axis = -1)

array([3, 7])

In [33]:
# соответственно сложение вдоль оси 0 соответсвует параметру axis = -2
np.sum(arr_2D, axis = -2)

array([4, 6])

__Массив 3D__

In [34]:
arr_3D = np.arange(12).reshape(2, 2, 3)
arr_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [35]:
arr_3D.shape

(2, 2, 3)

Сложение вдоль первой оси (axis = 0)

In [36]:
np.sum(arr_3D, axis = 0)

array([[ 6,  8, 10],
       [12, 14, 16]])

In [37]:
# если использовать индексы массива, то поэлементное сложение вдоль оси 0 можно
# реализовать следующим образом

# возьмем первую матрицу
arr_3D[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
# возбмем вторую матрицу
arr_3D[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
# сложим поэлементно
arr_3D[0] + arr_3D[1]

array([[ 6,  8, 10],
       [12, 14, 16]])

Сложение вдоль второй оси (axis = 1)

In [40]:
np.sum(arr_3D, axis = 1)

array([[ 3,  5,  7],
       [15, 17, 19]])

In [41]:
# Сложим поэлементарно
# первая матрица
arr_3D[0][0] + arr_3D[0][1]

array([3, 5, 7])

In [42]:
# вторая матрица
arr_3D[1][0] + arr_3D[1][1]

array([15, 17, 19])

Сложение вдоль третьей оси (axis = 2)

In [43]:
np.sum(arr_3D, axis = 2)

array([[ 3, 12],
       [21, 30]])

In [44]:
# Сложим поэлементарно
arr_3D[0][0][0] + arr_3D[0][0][1] + arr_3D[0][0][2]

3

In [45]:
arr_3D[0][1][0] + arr_3D[0][1][1] + arr_3D[0][1][2]

12

In [46]:
arr_3D[1][0][0] + arr_3D[1][0][1] + arr_3D[1][0][2]

21

In [47]:
arr_3D[1][1][0] + arr_3D[1][1][1] + arr_3D[1][1][2]

30

Сложение вдоль первой и второй осей ( axis = (0, 1))

In [48]:
np.sum(arr_3D, axis = (0, 1))

array([18, 22, 26])

Сложение вдоль трех осей (axis = (0, 1, 2))

In [49]:
np.sum(arr_3D, axis = (0, 1, 2))

66

In [50]:
# сложение вдоль трех осей установлено по умолчанию
np.sum(arr_3D)

66

### __Операции с массивами__

__Функция len()__

In [51]:
# по умолчанию функция len() выводит длину внешнего измерения (ось 0)
len(arr_3D)

2

In [52]:
# Что бы вывести, например длину внутреннего измерения, т.е. вектора 
# из трех элементов (ось 1), нужно воспользоваться индексом

len(arr_3D[0][0])

3

__Вхождение элемента в массив__

In [53]:
3 in arr_3D

True

In [54]:
13 in arr_3D

False

In [55]:
11 not in arr_3D

False

__Распаковка массива__

In [56]:
# Возьмем матрицу из трех строк и девяти столбцов
a = np.arange(1, 28).reshape(3, 9)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [57]:
# во внешнем измерении (ось 0) три элемента. Мы можем распаковать их в три переменные
x, y, z = a

In [58]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# теперь распакуем первый, последнийй и остальные элементы первой строки
# в отдельные элементы

x, *y, z = a[0]

print(x)
print(y)
print(z)

1
[2, 3, 4, 5, 6, 7, 8]
9


__Изменение элементов массива__

In [60]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
# заменим первый элемент первой строки по его индексу
arr_2D[0][0] = 2
arr_2D

array([[2, 2, 3],
       [4, 5, 6]])

In [62]:
# запишем значение 1 в первую строку
arr_2D[0] = 1
arr_2D

array([[1, 1, 1],
       [4, 5, 6]])

In [63]:
# пусть третий столбец состоит из 0
arr_2D[:, 2] = 0
arr_2D

array([[1, 1, 0],
       [4, 5, 0]])

In [64]:
# потренируемся на трехмерном массиве
arr_3D = np.arange(12).reshape(2, 2, 3)
arr_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [65]:
# Выберем второй столбец второй матрицы и заменим значения столбца 7 и 10 на 0 и 1
# при такой операции размер среза должен совпадать
# с количеством передаваемых значений

arr_3D[1, :, 1] = [0, 1]
arr_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  0,  8],
        [ 9,  1, 11]]])

In [66]:
 # Заменим все элементы массива на число 7 с помощью метода fill()
arr_3D.fill(7)
arr_3D

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])

### __Сортировка массива и обратный порядок его элементов__

__Функция np.sort()__

In [67]:
a = np.array([[4,8,2],[2,3,1]])
a

array([[4, 8, 2],
       [2, 3, 1]])

In [68]:
# По умолчанию сортировка идет с параметром axis = -1 (последняя ось)
np.sort(a)

array([[2, 4, 8],
       [1, 2, 3]])

In [69]:
# для двумерного массива это ось 1 (axis = 1)
np.sort(a, axis = 1)

array([[2, 4, 8],
       [1, 2, 3]])

In [70]:
# сортировка по оси 0 (axis = 0)
np.sort(a, axis = 0) 

array([[2, 3, 1],
       [4, 8, 2]])

In [71]:
# параметр axis = None, сначала возвращает одномерный массив, а затем сортирует его
np.sort(a, axis = None)

array([1, 2, 2, 3, 4, 8])

__Обратный порядок элементов массива__

In [72]:
# можно задать обратный порядок с помощью оператора среза с параметром шага -1
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [73]:
# обратный порядок можно совмецать со срезами
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])[-3:3:-1]

array([7, 6, 5, 4])

In [74]:
# возьмем двумерный массив
a = np.array([[4, 8,2], [2, 3, 1], [1, 7, 2]])
a

array([[4, 8, 2],
       [2, 3, 1],
       [1, 7, 2]])

In [75]:
# с помощью оператора среза можно задать обратный порядок по двум измерением
# такая запись аналогична параметру axis = (0, 1)
a[::-1, ::-1]

array([[2, 7, 1],
       [1, 3, 2],
       [2, 8, 4]])

In [76]:
# Мы можем задать обратный порядок только по внешнему или только внутреннем измерениям
# обратный порядок по внешнему (axis = 0)
a[::-1]

array([[1, 7, 2],
       [2, 3, 1],
       [4, 8, 2]])

In [77]:
# и внутреннему измерению (axis = 1)
a[:, ::-1]

array([[2, 8, 4],
       [1, 3, 2],
       [2, 7, 1]])

__Обратный порядок с помощью функции np.flipp()__


In [78]:
# тоже самое, что axis = (0, 1)
np.flip(a)

array([[2, 7, 1],
       [1, 3, 2],
       [2, 8, 4]])

In [79]:
# отдельно можно задать внешнее измерение
np.flip(a, axis = 0)

array([[1, 7, 2],
       [2, 3, 1],
       [4, 8, 2]])

In [80]:
# отдельно можно задать внутреннее измерение
np.flip(a, axis = 1)

array([[2, 8, 4],
       [1, 3, 2],
       [2, 7, 1]])

__Сортировка в убывающем порядке__

Функция np.sort() сортирует элементы только в возрастающем порядке

In [81]:
a = np.array([4, 2, 6, 1, 7, 3, 5])
a

array([4, 2, 6, 1, 7, 3, 5])

In [82]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7])

In [83]:
# применим одновременно оператор среза с параметром шага -1
np.sort(a)[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [84]:
# исходный массив при этом не изменился
a

array([4, 2, 6, 1, 7, 3, 5])

Можно воспользоваться и методом sort()

In [85]:
a[::-1].sort()
a

array([7, 6, 5, 4, 3, 2, 1])

In [86]:
# в данном случае исходный массив изменится
a 

array([7, 6, 5, 4, 3, 2, 1])

### __Изменение размерности__

__Метод .reshape()__

In [87]:
# возьмем простой трехмерный массив
arr_3D = np.arange(12).reshape(2, 2, 3)
arr_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [88]:
# в нем 12 элементов
arr_3D.size

12

С помощью метода .reshape() мы можем изменить количество измерений. 

In [89]:
# превратим 3D массив в матрицу с размерностью 2х6
# ВАЖНО чтобы общее количество элементов оставалось прежним
arr_2D = arr_3D.reshape(2, 6)
arr_2D

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

__Функция np.resize() и метод .resize()__


если мы хотим не только задать другую размерность, но и изменить общее количество элементов, то мы можем воспользоваться функцией np.resize() и методом .resize().

In [90]:
# функция np.resize() позволяет не сохранять прежнее количество элементов
# существующие элементы копируются в новые ячейки
np.resize(arr_2D, (3, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

Перед тем как воспользоваться методом .resize() нам необходимо создать копию массива arr_2D. Все дело в том, что переменная arr_2D ссылается на другой массив (в частности, на трехмерный массив arr_3D), а метод .resize() может работать только с исходным массивом.

In [91]:
arr_2D_copy = arr_2D.copy()

In [92]:
arr_2D_copy.resize(4, 6)
arr_2D_copy

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

__Методы .flatten() и .ravel()__

Метод .flatten() переводит («вытягивает») массив в одно измерение и создает копию исходного массива (как метод .copy()).

In [93]:
arr_3D.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Метод .ravel() делает то же самое, но не создает копию исходного массива и за счет этого быстрее, чем .flatten()

In [94]:
arr_3D.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

__Объект np.newaxis__

Объект np.newaxis добавляет измерение в уже существующем массиве

In [95]:
a = np.array([1, 2, 3])
print(a)
print(a.shape)

[1 2 3]
(3,)


In [96]:
# Мы можем добавить в этот массив новое первое измерение и, 
# таким образом, сделать существующее измерение вторым.
b = a[np.newaxis, :]
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [97]:
# Аналогично, мы можем добавить новое второе измерение, 
# а существующее измерение оставить первым.
c = a[:, np.newaxis]
print(c)
print(c.shape)

[[1]
 [2]
 [3]]
(3, 1)


__Функция np.expand_dims()__

Функция np.expand_dims() добавляет измерение, указанное в параметре axis. Возьмем двумерный массив.

In [98]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [99]:
# добавим внешнее измерение
np.expand_dims(a, axis = 0)

array([[[1, 2],
        [3, 4]]])

In [100]:
# теперь добавим измерение "по середине" 
np.expand_dims(a, axis = 1)

array([[[1, 2]],

       [[3, 4]]])

In [101]:
# добавим внутреннее измерение
np.expand_dims(a, axis = 2)

array([[[1],
        [2]],

       [[3],
        [4]]])

__Функция np.squeeze()__

In [102]:
# возьмем массив 4В, в котором первое и последнее измерения содержат 
# по одному элементу
arr_4D = np.arange(9).reshape(1, 3, 3, 1)
arr_4D

array([[[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]],

        [[6],
         [7],
         [8]]]])

In [103]:
# удалим эти измерения с помощью функции np.squeeze() 
np.squeeze(arr_4D)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [104]:
# новый массив имеет только 2 измерения
np.squeeze(arr_4D).shape

(3, 3)

### __Объдинение массивов__

__Функция np.concatenate()__ 

In [105]:
a = np.arange(4).reshape(2, 2)
a

array([[0, 1],
       [2, 3]])

In [106]:
b = np.arange(4, 8).reshape(2, 2)
b 

array([[4, 5],
       [6, 7]])

In [107]:
# объединим массивы вдоль оси 0 без добавления нового измерения
np.concatenate((a, b), axis = 0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [108]:
# объединим массивы вдоль оси 1
np.concatenate((a, b), axis = 1)

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

__Функция np.stack()__ 

Отличие функции np.stack() от np.concatenate() в том, что при объединении массивов мы добавляем новое измерение (новую ось).

In [109]:
# при axis = 0 добавляется просто новое измерение
np.stack((a, b), axis = 0) 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [110]:
# при axis = 1 объединяем первые и вторые строки двух массивов
np.stack((a, b), axis = 1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [111]:
# при axis = 2 объединяются элементы с одинаковыми индексами
np.stack((a, b), axis = 2)

array([[[0, 4],
        [1, 5]],

       [[2, 6],
        [3, 7]]])

### __Фильтр (маска) массива__

Задача фильтрации массива (или как еще говорят создания маски массива) встречается довольно часто. К примеру, предположим, что мы собрали показания прибора, однако из-за ошибки датчика часть из них оказалась некорректной, и для последующего анализа эти значения нужно удалить.

__Логическая маска (boolean mask)__

In [112]:
a = np.array([5, 7, -3, 4, 2, -4])

In [113]:
a > 0

array([ True,  True, False,  True,  True, False])

In [114]:
# применим маску
a[a > 0]

array([5, 7, 4, 2])

In [115]:
# отфильтрованные значениия можно заполнить например нулями
a[a < 0] = 0
a

array([5, 7, 0, 4, 2, 0])