In [1]:
import numpy as np

In [2]:
# создадим два массива
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
b = np.arange(6, 12).reshape(2, 3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

### __Сложение и вычитание массивов__

In [4]:
# поэлементарное сложение
a + b 

array([[ 6,  8, 10],
       [12, 14, 16]])

In [5]:
# сложение двух элементов внешнего измерения одного массива
a[0] + a[1]

array([3, 5, 7])

In [6]:
# сложение идет по внешнему измерению
[1, 1, 1] + a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# поэлементарное вычитание массивов
b - a

array([[6, 6, 6],
       [6, 6, 6]])

__Умножение и деление__

In [8]:
# Поэлементное умножение (произведение Адамара)
a * b 

array([[ 0,  7, 16],
       [27, 40, 55]])

In [9]:
# Поэлементное деление
a / b 

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [10]:
# размерность массива должна позволять выполнить поэлементарную операцию
np.array([[1, 2], [3, 4], [5, 6]]) / np.array([1, 2])

array([[1., 1.],
       [3., 2.],
       [5., 3.]])

In [11]:
# Numpy позволяет умножать и делить на число
2 * a

array([[ 0,  2,  4],
       [ 6,  8, 10]])

__Другие математические операции__

__np.max()__ 

In [12]:
# поиск максимального значения
np.max(a)

5

In [13]:
# найдем максимальное значение вдоль второго (последнего измерения)
np.max(a, axis = 1)

array([2, 5])

Большинство функций имеют соответствующий метод, который приводит к точно такому же результату.

In [14]:
np.max(a) == a.max()

True

In [15]:
a.max()

5

### __Логические операции__

__Сравнение массивов__

In [16]:
# возьмем два одномерных вектора
a = np.array([1, 2, 3], float)
b = np.array([1, 3, 2], float)

In [17]:
# проверим поэлементарное равентсво этих массивов
a == b 

array([ True, False, False])

In [18]:
# сравним массивы поэлементно
a < b 

array([False,  True, False])

In [19]:
# можно сравнить с помощью специальной функции np.less()
np.less(a, b) 

array([False,  True, False])

In [20]:
# можно сравнить элементы массива с числом
a > 1

array([False,  True,  True])

__np.logical_and()__

In [21]:
# выведем True только если значение массива а больше нуля И меньше трех
np.logical_and(a > 0, a < 3)

array([ True,  True, False])

__np.logical_or()__

In [22]:
# выведем значениие True, если элемент массива b меньше трех или если элемент 
# равен 1
np.logical_or(b < 3, b == 1)

array([ True, False,  True])

__np.logical_xor__

In [23]:
# выведем True, если элемент массива a больше одного или (но не одновременно)
# элемент массива b меньше трех
np.logical_xor(a > 1, b < 3)

array([ True,  True, False])

__np.logical_not()__

In [24]:
# все элементы станут ложными
np.logical_not(a)

array([False, False, False])

В Питоне все числа кроме нуля считаются истинными, ноль наоборот приравнивается к ложному значению. Убедимся в этом с помощью двух несложных примеров

In [25]:
# условие if выполняется, если выражение истинно, т.е. в данном случае 
# если и 2, и - 2,5 истинны
if 2 and -2.5:
    print('both are True')

both are True


In [26]:
# если НЕ ноль истинно, условие так же выполняется
if not 0:
    print('zero is False')

zero is False


__Функции np.all() и np.any()__

In [27]:
# Создадим массив состоящий из булевых значений
a_boolean = [[True, False], [True, True]]

Функция __np.all()__ позволяет проверить, все ли элементы массива оцениваются как истинные

In [28]:
np.all(a_boolean)

False

Функция __np.any()__ наоборот проверяет, истинно ли хотя бы одно значениие

In [29]:
np.any(a_boolean)

True

__Функция np.where()__

In [30]:
scores = np.array([5, 2, 4, 3, 2, 4])

Необходимо заменить оценку 2 на "Не сдал", а остальные на "Сдал".

Сначала создадим массив из логических значений

In [31]:
# True если результат больше двух

condition = scores > 2
condition

array([ True, False,  True,  True, False,  True])

Теперь создадим списки с категориями, такой же длины, как и исходный массив scores 


In [32]:
pass_list = ['Pass'] * len(scores)
fail_list = ['Fail'] * len(scores)

In [33]:
pass_list

['Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass']

Передадим функции np.where() массив с логическими значениями и два списка

In [34]:
np.where(condition, pass_list, fail_list)

array(['Pass', 'Fail', 'Pass', 'Pass', 'Fail', 'Pass'], dtype='<U4')

### __Векторизация и трансляция__

__Векторизация__

Сравним время исполнения кода с циклами и без них на простом примере. Вначале создадим два длинных одномерных массива.

In [35]:
np.random.seed(42)

# создадим два массива по миллиону случайных чисел в интервале [0, 1)
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

Используем цикл for и list comprehension для поэлементного умножения двух векторов

In [36]:
%time res = [i * j for i, j in zip(v1, v2)]

CPU times: total: 31.2 ms
Wall time: 102 ms


Решим ту же задачу, но уже с помощью векторизированного кода

In [37]:
%time res_2 = v1 * v2

CPU times: total: 0 ns
Wall time: 2.84 ms


Убедимся что получившиеся массивы полностью идентичны

In [38]:
np.array_equal(res, res_2)

True

__Трансляция__ 

Довольно часто бывает так, что массивы, над которыми выполняют какую-либо операцию, обладают разной размерностью. Предположим, что мы хотим сложить одномерный массив с массивом нулевой размерности (числом).

В этом случае, для того чтобы сделать возможной векторизацию сложения, Numpy предварительно увеличивает меньший массив (число) до размеров большего (вектора) и затем выполняет сложение без использования цикла. Такой подход называется трансляцией (broadcasting).

In [39]:
# создадим одномерный вектор
v3 = np.array([1, 2, 3, 4, 5])

# и вектор с нулевым измерением (число)
n = np.array(6)

# размерность вектора и числа не совпадает
v3.shape, n.shape

((5,), ())

Прежде чем выполнить векторизованную операцию (сложение), размерность числа увеличивается до размерности вектора.



In [40]:
v3 + n

array([ 7,  8,  9, 10, 11])

### __Умножение векторов, матриц и тензоров__

__Скалярное произведение векторов__

Скалярное произведение векторов осуществляется с помощью функции np.dot()

In [41]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

# вычислим скалярное произведение
np.dot(a, b)

14

В русском языке под скалярным произведением понимается поэлементное умножение и сложение получившихся произведений. Вероятно, такое название связано с тем, что результатом операции будет число (скаляр). При этом если мы просто хотим провести поэлементное (покомпонентное) умножение, речь идет произведении Адамара. Также возможно умножение вектора или матрицы на число.

__Произведение матрицы и вектора__

In [42]:
# создадим матрицу данных
c = np.arange(1, 10).reshape(3, 3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
# умножим матрицу на вектор
np.dot(c, a)

array([14, 32, 50])

__Умножение двух матриц__

In [44]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
b = np.arange(6).reshape(3, 2)[::-1, ::-1]
b

array([[5, 4],
       [3, 2],
       [1, 0]])

In [46]:
np.dot(a, b)

array([[ 5,  2],
       [32, 20]])

__Тензорное произведение__

In [48]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
b

array([[5, 4],
       [3, 2],
       [1, 0]])

In [50]:
# повторим умножение матриц с помощью функции np.dot()
np.dot(a, b)

array([[ 5,  2],
       [32, 20]])

Идея np.tensordot() заключается в том, чтобы явно указать оси массива, по которым будет происходить покомпонентное умножение и сложение получившихся произведений (по-английски такое сокращение еще называют sum-reduction). Делается это с помощью параметра axes.

In [52]:
np.tensordot(a, b, axes = (1, 0))

array([[ 5,  2],
       [32, 20]])

In [54]:
np.tensordot(a, b, axes = (0, 1))

array([[12,  6,  0],
       [21, 11,  1],
       [30, 16,  2]])